services:
  lidar:
    build: ./docker
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./rplidar_ros:/root/src/rplidar_ros
      - ./map:/root/src/map
      - ./planners:/root/src/planners
    command: 
      sleep infinity

